name: Build

on:
  push:
    branches: [main]
    tags: ['v*']

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: linux-x64
          - os: ubuntu-latest
            target: x86_64-pc-windows-msvc
            suffix: windows-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: macos-arm64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile binaries (linux)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          mkdir -p dist
          set -e
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-bidder-${{ matrix.suffix }} atproto-market/hono-bidder/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/request-vm-ssh-${{ matrix.suffix }} atproto-market/request-vm-ssh/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/compute-contract-gateway-${{ matrix.suffix }} atproto-market/hono-compute-contract-gateway/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-policy-${{ matrix.suffix }} atproto-market/hono-policy/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-plc-${{ matrix.suffix }} atproto-market/hono-plc/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-pds-${{ matrix.suffix }} hono-pds/main.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-did-key-ingress-proxy-${{ matrix.suffix }} did-key-ingress-proxy/hono-did-key-ingress-proxy/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-did-key-ingress-proxy-subscriber-${{ matrix.suffix }} did-key-ingress-proxy/hono-did-key-ingress-proxy-subscriber/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/tunnel-subscriber-${{ matrix.suffix }} did-key-ingress-proxy/hono-did-key-ingress-proxy-tunnel-subscriber/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/tunnel-${{ matrix.suffix }} did-key-ingress-proxy/hono-did-key-ingress-proxy-tunnel/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-compute-provider-${{ matrix.suffix }} hono-compute-provider/hono-compute-provider/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-compute-deno-${{ matrix.suffix }} deno-worker-sandbox/hono-compute-deno/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-sandbox-${{ matrix.suffix }} deno-worker-sandbox/hono-sandbox/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-http-static-${{ matrix.suffix }} typescript-helpers/hono-http-static/mod.ts

      - name: Compile binaries (macos)
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          mkdir -p dist
          set -e
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-bidder-${{ matrix.suffix }} atproto-market/hono-bidder/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/request-vm-ssh-${{ matrix.suffix }} atproto-market/request-vm-ssh/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/compute-contract-gateway-${{ matrix.suffix }} atproto-market/hono-compute-contract-gateway/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-policy-${{ matrix.suffix }} atproto-market/hono-policy/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-plc-${{ matrix.suffix }} atproto-market/hono-plc/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-pds-${{ matrix.suffix }} hono-pds/main.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-did-key-ingress-proxy-${{ matrix.suffix }} did-key-ingress-proxy/hono-did-key-ingress-proxy/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-did-key-ingress-proxy-subscriber-${{ matrix.suffix }} did-key-ingress-proxy/hono-did-key-ingress-proxy-subscriber/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/tunnel-subscriber-${{ matrix.suffix }} did-key-ingress-proxy/hono-did-key-ingress-proxy-tunnel-subscriber/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/tunnel-${{ matrix.suffix }} did-key-ingress-proxy/hono-did-key-ingress-proxy-tunnel/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-compute-provider-${{ matrix.suffix }} hono-compute-provider/hono-compute-provider/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-compute-deno-${{ matrix.suffix }} deno-worker-sandbox/hono-compute-deno/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-sandbox-${{ matrix.suffix }} deno-worker-sandbox/hono-sandbox/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-http-static-${{ matrix.suffix }} typescript-helpers/hono-http-static/mod.ts

      - name: Compile binaries (windows)
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          mkdir -p dist
          set -e
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-bidder-${{ matrix.suffix }}.exe atproto-market/hono-bidder/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/request-vm-ssh-${{ matrix.suffix }}.exe atproto-market/request-vm-ssh/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/compute-contract-gateway-${{ matrix.suffix }}.exe atproto-market/hono-compute-contract-gateway/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-policy-${{ matrix.suffix }}.exe atproto-market/hono-policy/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-plc-${{ matrix.suffix }}.exe atproto-market/hono-plc/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-pds-${{ matrix.suffix }}.exe hono-pds/main.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-did-key-ingress-proxy-${{ matrix.suffix }}.exe did-key-ingress-proxy/hono-did-key-ingress-proxy/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-did-key-ingress-proxy-subscriber-${{ matrix.suffix }}.exe did-key-ingress-proxy/hono-did-key-ingress-proxy-subscriber/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/tunnel-subscriber-${{ matrix.suffix }}.exe did-key-ingress-proxy/hono-did-key-ingress-proxy-tunnel-subscriber/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/tunnel-${{ matrix.suffix }}.exe did-key-ingress-proxy/hono-did-key-ingress-proxy-tunnel/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-compute-provider-${{ matrix.suffix }}.exe hono-compute-provider/hono-compute-provider/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-compute-deno-${{ matrix.suffix }}.exe deno-worker-sandbox/hono-compute-deno/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-sandbox-${{ matrix.suffix }}.exe deno-worker-sandbox/hono-sandbox/mod.ts
          deno compile --allow-all --target ${{ matrix.target }} --output dist/hono-http-static-${{ matrix.suffix }}.exe typescript-helpers/hono-http-static/mod.ts

      - name: Build SPAs
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cd compute-spa && deno run -A build.ts
          tar -czf ../dist/compute-spa.tar.gz -C dist .
          cd ../did-key-associator && deno run -A build.ts
          tar -czf ../dist/did-key-associator.tar.gz -C dist .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deno-binaries-${{ matrix.suffix }}
          path: |
            dist/*
